version: '3.7'

services:

  client:
    env_file:
      - ./client/.env
    build:
      context: /client
      dockerfile: Dockerfile
    container_name: client
    image: social_media_client:${APP_VERSION:-latest}
    hostname: client
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
    networks:
      - backend
    tty: true
    restart: always
    depends_on:
      - server


  server:
    env_file:
      - ./server/.env
    build:
      context: /server
      dockerfile: Dockerfile
    container_name: server
    image: social_media_server:${APP_VERSION:-latest}
    hostname: server
    ports:
      - ${APP_PORT:-5000}:${APP_PORT:-5000}
    networks:
      - backend
    tty: true
    restart: always
    environment:
      APP_ENV: "${APP_ENV}"

networks:
  backend:
    driver: 'bridge'

volumes:
  db_data:
    name: volumes_dir
